#!/bin/bash

echo ======================================================
echo "RUNNING noregerts WILL REALLY MESS UP YOUR DEVICE"
echo "RUNNING noregerts WILL REALLY MESS UP YOUR DEVICE"
echo "RUNNING noregerts WILL REALLY MESS UP YOUR DEVICE"
echo "RUNNING noregerts WILL REALLY MESS UP YOUR DEVICE"
echo "RUNNING noregerts WILL REALLY MESS UP YOUR DEVICE"
echo "RUNNING noregerts WILL REALLY MESS UP YOUR DEVICE"
echo "RUNNING noregerts WILL REALLY MESS UP YOUR DEVICE"
echo "RUNNING noregerts WILL REALLY MESS UP YOUR DEVICE"
echo "RUNNING noregerts WILL REALLY MESS UP YOUR DEVICE"
echo "RUNNING noregerts WILL REALLY MESS UP YOUR DEVICE"
echo "RUNNING noregerts WILL REALLY MESS UP YOUR DEVICE"
echo "RUNNING noregerts WILL REALLY MESS UP YOUR DEVICE"
echo ======================================================
